const TagsActionTypes = {
  FETCH_TAGS_REQUEST: "FETCH_TAGS_REQUEST",
  FETCH_TAGS_SUCCESS: "FETCH_TAGS_SUCCESS",
  FETCH_TAGS_FAILURE: "FETCH_TAGS_FAILURE",

  ADD_TAG_REQUEST: "ADD_TAG_REQUEST",
  ADD_TAG_SUCCESS: "ADD_TAG_SUCCESS",
  ADD_TAG_FAILURE: "ADD_TAG_FAILURE",
};

export default TagsActionTypes;
